import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#f0bd8b",
        "on-error": "#ffffff",
        "surface-container-highest": "#e5e2da",
        "glass-surface": "rgba(255, 255, 255, 0.4)",
        "primary-fixed": "#ffdcbd",
        "on-primary-container": "#5b3912",
        "surface": "#fcf9f0",
        "surface-container-high": "#ebe8df",
        "surface-variant": "#e5e2da",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-low": "#f6f3eb",
        "glow-gold": "rgba(212, 163, 115, 0.3)",
        "on-error-container": "#93000a",
        "on-surface": "#1c1c17",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#1f1b0d",
        "inverse-surface": "#31312b",
        "on-secondary-container": "#656464",
        "surface-container-lowest": "#ffffff",
        "deep-ink": "#0F0F0F",
        "primary": "#7d562d",
        "on-tertiary": "#ffffff",
        "secondary-container": "#e4e2e1",
        "inverse-on-surface": "#f3f1e8",
        "outline": "#82756a",
        "secondary-fixed-dim": "#c8c6c6",
        "primary-fixed-dim": "#f0bd8b",
        "tertiary-fixed-dim": "#cec6af",
        "glass-border": "rgba(255, 255, 255, 0.6)",
        "background": "#fcf9f0",
        "tertiary-container": "#b4ac96",
        "error-container": "#ffdad6",
        "tertiary": "#645e4b",
        "on-primary-fixed": "#2c1600",
        "on-primary": "#ffffff",
        "surface-tint": "#7d562d",
        "outline-variant": "#d4c4b7",
        "on-secondary": "#ffffff",
        "primary-container": "#d4a373",
        "tertiary-fixed": "#ebe2ca",
        "surface-dim": "#dcdad1",
        "surface-bright": "#fcf9f0",
        "surface-container": "#f1eee5",
        "on-tertiary-fixed-variant": "#4c4735",
        "on-surface-variant": "#50453b",
        "on-background": "#1c1c17",
        "on-secondary-fixed-variant": "#474747",
        "secondary": "#5f5e5e",
        "on-primary-fixed-variant": "#623f18",
        "secondary-fixed": "#e4e2e1",
        "on-tertiary-container": "#45402f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "32px",
        "margin-desktop": "80px",
        "section-gap": "160px",
        "margin-mobile": "24px",
        "container-max": "1440px",
        "unit": "8px"
      },
      fontFamily: {
        "body-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "overline": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-sm": ["var(--font-syne)", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "display-lg-mobile": ["var(--font-syne)", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "display-lg": ["var(--font-syne)", "sans-serif"],
        "headline-md": ["var(--font-syne)", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "overline": ["12px", { lineHeight: "16px", letterSpacing: "0.4em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-lg": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
